# Generated by Django 3.1.4 on 2021-01-29 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Maximum 30 Characters', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maximum 30 Characters', max_length=30)),
                ('summary', models.CharField(help_text='Exactly 115 Characters', max_length=250)),
                ('featured_image', models.ImageField(default='', upload_to='featured_image/%Y%m%d')),
                ('demo_url', models.URLField(blank=True, help_text='Provide demo URL Address', max_length=250)),
                ('category', models.ForeignKey(help_text='Select Your Category', on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
