# Generated by Django 3.1.4 on 2021-01-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Select Your Category', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category'),
        ),
    ]
